version: "3.9"
services:
  pottery-api:
    image: 1029bobby/pottery-api-cloud:0.0.1.RELEASE
    ports:
      - "80:3000"
    environment:
      - DB_HOST=
    restart: always
    depends_on:
      - pottery-python
    networks:
      - pottery-network

  pottery-python:
    image: 1029bobby/pottery-python-cloud:0.0.1.RELEASE
    ports:
      - "3001:3001"
    restart: always
    networks:
      - pottery-network

networks:
  pottery-network:
